/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try (Scanner input = new Scanner(System.in)) {
            System.out.println("\nSelecione o exercício para testar os objetos (1-3):");
            System.out.println("1 - Exercicio Um");
            System.out.println("2 - Exercicio Dois");
            System.out.println("3 - Exercicio Tres");
            System.out.print("> ");
            int opcao = input.nextInt();
            
            switch (opcao) {
                case 1 -> exercicioUm();
                case 2 -> exercicioDois();
                case 3 -> exercicioTres();
                default -> System.out.println("Opção inválida.");
            }
        }
    }

    public static void exercicioUm() {
        System.out.println("Exercício 1");
    }

    public static void exercicioDois() {
        System.out.println("Exercício 2");
    }

    public static void exercicioTres() {
        System.out.println("Exercício 3");
    }
}
