/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.util.Scanner;

import ifsc.poo.ClassesExercicios.ExercicioDois.MainDois;
import ifsc.poo.ClassesExercicios.ExercicioTres.MainTres;
import ifsc.poo.ClassesExercicios.ExercicioUm.MainUm;

public class App {
    public static void main(String[] args) {
        try (Scanner input = new Scanner(System.in)) {
            System.out.println("\nSelecione o exercício para testar os objetos (1-3):");
            System.out.println("1 - Exercicio Um");
            System.out.println("2 - Exercicio Dois");
            System.out.println("3 - Exercicio Tres");
            System.out.print("> ");
            int opcao = input.nextInt();

            switch (opcao) {
                case 1 -> exercicioUm();
                case 2 -> exercicioDois();
                case 3 -> exercicioTres();
                default -> System.out.println("Opção inválida.");
            }
        }
    }

    public static void exercicioUm() {
        MainUm.main(new String[]{});
    }

    public static void exercicioDois() {
        MainDois.main(new String[]{});
    }

    public static void exercicioTres() {
        MainTres.main(new String[]{});
    }
}
