package ifsc.poo.ClassesExercicios.ExercicioUm;

public class Gerenciador {
    public static boolean cadastrarUsuario(String login, String senha){
        return true;
    }

    public static boolean removerUsuario(String login){
        return true;
    }

    public static Usuario[] listarLogins(){
        Usuario[] user = new Usuario[10];

        return user;
    }

    public static boolean autenticar(String login, String senha){
        return true;
    }

}